name = "asset-manager-api"
main = "worker.js"
compatibility_date = "2026-08-25"

[[kv_namespaces]]
binding = "ASSET_STORE"
id = "0e839f63e1504cdf81098617b17a22f7"

[vars]
ALLOWED_ORIGIN = "https://assets-management-8os.pages.dev"
